version: '3.4'
services:
  netbox:
    ports:
      - 8004:8080
    volumes:
    - netbox_configuration:/etc/netbox/config
    - netbox_reports:/etc/netbox/reports
    - netbox_scripts:/etc/netbox/scripts
